version: '2'

services:
    proxy:
        image: proxy
        ports:
            - 8080:8080
            - 8081:8081
        restart: always

    nginx:
        depends_on:
            - proxy
        image: nginx:alpine
        restart: always

    drupal:
        depends_on:
            - proxy
        image: drupal:8-apache
        volumes:
        - /var/www/html/modules
        - /var/www/html/profiles
        - /var/www/html/themes
        # this takes advantage of the feature in Docker that a new anonymous
        # volume (which is what we're creating here) will be initialized with the
        # existing content of the image at the same location
        - /var/www/html/sites
        restart: always